#!/usr/bin/env bash

if [[ $BASH_VERSION =~ ^3 ]]; then
	/usr/local/bin/bash -c 'echo $BASH_VERSION' | grep -q ^4 && exec /usr/local/bin/bash --login
fi

[[ -f $HOME/.bashrc ]] && . $HOME/.bashrc

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='bobby'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/xvzf/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# Path to the bash it configuration
export BASH_IT="$HOME/.bash-it"
# Load Bash It
source $BASH_IT/bash_it.sh

HISTFILESIZE=unlimited
IGNOREEOF=3
# enable this to try iterm2 shell integration (not ready to try yet 6/16/2016)
#source ~/.iterm2_shell_integration.bash

# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

